# Generated by Django 5.0.6 on 2026-06-09 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('KPI_CARD', 'KPI card'), ('BAR_CHART', 'Bar chart'), ('LINE_CHART', 'Line chart'), ('PIE_CHART', 'Pie chart'), ('DATA_TABLE', 'Data table'), ('TEXT_BLOCK', 'Text block')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('config_json', models.JSONField(blank=True, null=True)),
                ('position_json', models.JSONField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='sheets.dashboardsheet')),
            ],
            options={
                'db_table': 'dashboard_widgets',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
