# Generated by Django 5.0.6 on 2026-06-09 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoOrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('region', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('customer_type', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'demo_order_records',
            },
        ),
        migrations.CreateModel(
            name='DemoOrganizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.CharField(max_length=20)),
                ('organization_name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('organization_type', models.CharField(blank=True, default='', max_length=100)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=100)),
                ('contact_email', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'demo_organization_records',
            },
        ),
        migrations.CreateModel(
            name='DemoProcurementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100)),
                ('lot_title', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, default='', max_length=255)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('winning_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('competitor_count', models.IntegerField(null=True)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('result', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'demo_procurement_records',
            },
        ),
        migrations.CreateModel(
            name='DemoProviderSpeedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('region', models.CharField(max_length=255)),
                ('provider_name', models.CharField(max_length=255)),
                ('download_speed', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('upload_speed', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('latency_ms', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quality_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'demo_provider_speed_records',
            },
        ),
        migrations.CreateModel(
            name='DemoRevenueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('region', models.CharField(max_length=255)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_installation_requests', models.IntegerField()),
                ('churn_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'demo_revenue_records',
            },
        ),
        migrations.CreateModel(
            name='DemoSalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField()),
                ('region', models.CharField(blank=True, default='', max_length=255)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('tariff_name', models.CharField(blank=True, default='', max_length=255)),
                ('offer_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('conversion_probability', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'demo_sales_records',
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('business_purpose', models.TextField(blank=True, default='')),
                ('owner_name', models.CharField(blank=True, default='', max_length=255)),
                ('access_level', models.CharField(choices=[('ADMIN_ONLY', 'Admin only'), ('ANALYST_ONLY', 'Analyst only'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee'), ('PUBLIC_INTERNAL', 'Public internal')], default='EMPLOYEE', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=50)),
                ('tags', models.TextField(blank=True, default='')),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dashboards', to='categories.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboards',
                'ordering': ['-last_updated_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DashboardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
                ('can_view', models.BooleanField(default=True)),
                ('can_export', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='dashboards.dashboard')),
            ],
            options={
                'db_table': 'dashboard_permissions',
                'unique_together': {('dashboard', 'role_name')},
            },
        ),
    ]
